apiVersion: v1
kind: ServiceAccount
metadata:
  name: rolemapper-sa
  namespace: rolemapper-dev
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rolemapper-configmap-updater
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["aws-auth"]
  verbs: ["update", "get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolemapper-configmap-updater-binding
subjects:
  - kind: ServiceAccount
    name: rolemapper-sa
    namespace: rolemapper-dev
roleRef:
  kind: ClusterRole
  name: rolemapper-configmap-updater
  apiGroup: rbac.authorization.k8s.io